"""Generate agent/knowledge.py from Razorpay's PUBLIC documentation.

    python scripts/gen_knowledge.py

## What this exists to keep honest

The agent is entitled to Razorpay's published error documentation -- any
merchant can read it, so withholding it would make the benchmark artificially
hard and would not resemble anything real. What the agent is *not* entitled to
is the simulator's answer key.

Those two things live in the same source file (`sim/taxonomy.py`), so this
script does the separation mechanically rather than trusting anyone to remember
it:

  * **Carried over** -- `reason`, `description`, `next_steps`, and the recovery
    class derived from the documented next steps. All public.

  * **Stripped** -- `base_recovery_prob`. That is our hidden modelling
    assumption and appears nowhere in Razorpay's docs. If the agent could read
    it, the whole exercise would be circular.

  * **Omitted entirely** -- every reason marked `held_out`. Not because they
    are secret, but because a real rulebook lags: gateway reason strings appear
    in production faster than anyone updates the mapping. Those reasons still
    occur in the batch; the agent simply has no entry for them and has to work
    it out. That is the generalisation test.

The generated file is committed, so `agent/` never imports `sim/` at runtime and
the boundary test stays satisfied.
"""

from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from sim.taxonomy import ERRORS  # noqa: E402

OUT = pathlib.Path(__file__).resolve().parent.parent / "agent" / "knowledge.py"

HEADER = '''"""The merchant's rulebook, derived from Razorpay's public error documentation.

GENERATED BY scripts/gen_knowledge.py -- DO NOT EDIT BY HAND.

Source: https://razorpay.com/docs/errors/payments/list/

This is what any Razorpay merchant can look up. It carries each documented
failure reason, Razorpay's own description, Razorpay's own recommended next
step, and the recovery class those next steps imply.

Two things are deliberately absent:

  * **No recovery probabilities.** Razorpay does not publish them and neither do
    we. The agent has to form its own view of how likely a recovery is.

  * **No entry for {held_out} of the reasons that occur in production.** A real
    rulebook always lags -- gateway reason strings show up faster than anyone
    maps them. When the agent meets one of these it gets `None` from
    `documented_class()` and has to reason from the description text alone.
    This is the generalisation test, and it is where a language model has to
    earn its place over a lookup table.

The rules-engine baseline in evaluation/baselines.py is built from exactly this
file, so the comparison is fair: both policies get the public documentation, and
neither gets the answer key.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DocumentedReason:
    reason: str
    description: str
    next_steps: str
    recovery_class: str


RULEBOOK: dict[str, DocumentedReason] = {{
'''

FOOTER = '''}}

# Reasons Razorpay documents as risk, compliance or merchant-side integration
# failures. Re-presenting one of these is not merely wasteful: programmatically
# retrying a risk-declined payment is the behaviour that gets a merchant's MID
# reviewed. agent/policy.py treats this set as a hard veto that the model cannot
# talk its way past.
NEVER_RETRY: frozenset[str] = frozenset(
    r for r, d in RULEBOOK.items() if d.recovery_class in ("hard_stop", "merchant_fix")
)

# Razorpay documents this reason as carrying no specific gateway error code, so
# the string alone cannot tell you what went wrong. The right action has to be
# inferred from context: method, issuer health, amount, customer history.
AMBIGUOUS: frozenset[str] = frozenset({{"payment_failed"}})


def documented_class(reason: str) -> str | None:
    """The recovery class Razorpay's docs imply, or None if unmapped.

    `None` is the interesting case. It means either a reason our rulebook has
    not caught up with, or one Razorpay documents ambiguously. Either way the
    agent is on its own.
    """
    entry = RULEBOOK.get(reason)
    return entry.recovery_class if entry else None


def describe(reason: str) -> str:
    """Razorpay's own description, for feeding to a model. Falls back to the
    raw reason string when we have no entry -- which is precisely when the
    model has to work hardest."""
    entry = RULEBOOK.get(reason)
    return entry.description if entry else f"(undocumented reason: {{reason}})"


KNOWN_REASONS: frozenset[str] = frozenset(RULEBOOK)
'''


def main() -> int:
    kept = [e for e in ERRORS if not e.held_out]
    dropped = [e for e in ERRORS if e.held_out]

    lines = [HEADER.format(held_out=len(dropped))]
    for e in sorted(kept, key=lambda x: x.reason):
        lines.append(f'    "{e.reason}": DocumentedReason(')
        lines.append(f'        reason="{e.reason}",')
        lines.append(f"        description={_q(e.description)},")
        lines.append(f"        next_steps={_q(e.next_steps)},")
        lines.append(f'        recovery_class="{e.recovery_class.value}",')
        lines.append("    ),")
    lines.append(FOOTER)

    OUT.write_text("\n".join(lines).replace("{{", "{").replace("}}", "}"), encoding="utf-8")

    print(f"wrote {OUT.relative_to(OUT.parent.parent)}")
    print(f"  documented reasons : {len(kept)}")
    print(f"  withheld (held_out): {len(dropped)}")
    for e in sorted(dropped, key=lambda x: x.reason):
        print(f"      - {e.reason}  ({e.recovery_class.value})")
    print("  recovery probabilities carried over: 0  (by construction)")
    return 0


def _q(s: str) -> str:
    """Emit a Python string literal, wrapping long text readably."""
    escaped = s.replace("\\", "\\\\").replace('"', '\\"')
    if len(escaped) <= 62:
        return f'"{escaped}"'
    words, out, cur = escaped.split(" "), [], ""
    for w in words:
        if len(cur) + len(w) + 1 > 62:
            out.append(cur)
            cur = w
        else:
            cur = f"{cur} {w}".strip()
    if cur:
        out.append(cur)
    body = "\n".join(f'            "{part} "' for part in out[:-1])
    return "(\n" + body + f'\n            "{out[-1]}"\n        )'


if __name__ == "__main__":
    raise SystemExit(main())
