"""The merchant's rulebook, derived from Razorpay's public error documentation.

GENERATED BY scripts/gen_knowledge.py -- DO NOT EDIT BY HAND.

Source: https://razorpay.com/docs/errors/payments/list/

This is what any Razorpay merchant can look up. It carries each documented
failure reason, Razorpay's own description, Razorpay's own recommended next
step, and the recovery class those next steps imply.

Two things are deliberately absent:

  * **No recovery probabilities.** Razorpay does not publish them and neither do
    we. The agent has to form its own view of how likely a recovery is.

  * **No entry for 10 of the reasons that occur in production.** A real
    rulebook always lags -- gateway reason strings show up faster than anyone
    maps them. When the agent meets one of these it gets `None` from
    `documented_class()` and has to reason from the description text alone.
    This is the generalisation test, and it is where a language model has to
    earn its place over a lookup table.

The rules-engine baseline in evaluation/baselines.py is built from exactly this
file, so the comparison is fair: both policies get the public documentation, and
neither gets the answer key.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DocumentedReason:
    reason: str
    description: str
    next_steps: str
    recovery_class: str


RULEBOOK: dict[str, DocumentedReason] = {

    "authentication_failed": DocumentedReason(
        reason="authentication_failed",
        description=(
            "The payment failed as 3D secure, or OTP authentication failed. "
            "This could happen if the user cancels the payment on the "
            "authentication (OTP submit) screen or enters incorrect "
            "authentication details such as OTP."
        ),
        next_steps=(
            "The customer must enter correct authentication details to "
            "complete the payment."
        ),
        recovery_class="nudge_customer",
    ),
    "bank_account_invalid": DocumentedReason(
        reason="bank_account_invalid",
        description=(
            "The bank account is not valid. The customer or bank could have "
            "closed the account."
        ),
        next_steps=(
            "The customer must try using a valid bank account or another "
            "method."
        ),
        recovery_class="switch_rail",
    ),
    "bank_cutoff_in_progress": DocumentedReason(
        reason="bank_cutoff_in_progress",
        description=(
            "Bank CBS cutoff is in progress. This is a periodic event at "
            "the bank's end."
        ),
        next_steps="The customer must retry.",
        recovery_class="retry_same",
    ),
    "bank_not_available": DocumentedReason(
        reason="bank_not_available",
        description="Bank is not available due to a downtime or a technical issue.",
        next_steps="The customer must retry.",
        recovery_class="retry_same",
    ),
    "bank_not_enabled": DocumentedReason(
        reason="bank_not_enabled",
        description=(
            "The selected bank to complete the transaction is not enabled "
            "for your business."
        ),
        next_steps="Please reach out to Razorpay to enable the selected bank.",
        recovery_class="merchant_fix",
    ),
    "bank_technical_error": DocumentedReason(
        reason="bank_technical_error",
        description=(
            "The issuing bank was facing technical problems at the moment "
            "the payment was attempted. This usually occurs when the Core "
            "Banking System encounters a technical error while processing "
            "the payment."
        ),
        next_steps=(
            "The customer must try using another bank account or another "
            "method."
        ),
        recovery_class="retry_same",
    ),
    "card_declined": DocumentedReason(
        reason="card_declined",
        description="The card has been declined.",
        next_steps="The customer must retry with a different card or method.",
        recovery_class="switch_rail",
    ),
    "card_expired": DocumentedReason(
        reason="card_expired",
        description="The card has expired.",
        next_steps="The customer must retry with a valid card.",
        recovery_class="switch_rail",
    ),
    "card_network_not_enabled": DocumentedReason(
        reason="card_network_not_enabled",
        description=(
            "The card's network (Visa, Mastercard, etc.) is not enabled for "
            "the merchant."
        ),
        next_steps="Please reach out to Razorpay to enable the card network.",
        recovery_class="merchant_fix",
    ),
    "card_not_enrolled": DocumentedReason(
        reason="card_not_enrolled",
        description="The card is not enrolled for this payment method.",
        next_steps=(
            "Customer needs to enroll the card for this payment method or "
            "use another card."
        ),
        recovery_class="switch_rail",
    ),
    "compliance_violation": DocumentedReason(
        reason="compliance_violation",
        description="The payment violates compliance requirements.",
        next_steps="Please ensure the payment meets all compliance requirements.",
        recovery_class="hard_stop",
    ),
    "credit_limit_exceeded": DocumentedReason(
        reason="credit_limit_exceeded",
        description="The customer's credit limit has been exceeded.",
        next_steps=(
            "Customer needs to reduce the amount or use another payment "
            "method."
        ),
        recovery_class="retry_later_funds",
    ),
    "debit_instrument_blocked": DocumentedReason(
        reason="debit_instrument_blocked",
        description=(
            "The customer is using a blocked card to complete the payment. "
            "The card could have been blocked by the issuer or by customers "
            "themselves."
        ),
        next_steps="The customer must retry with a different card or method.",
        recovery_class="switch_rail",
    ),
    "debit_instrument_inactive": DocumentedReason(
        reason="debit_instrument_inactive",
        description="The debit instrument is inactive.",
        next_steps=(
            "Customer needs to activate the instrument or use another "
            "payment method."
        ),
        recovery_class="switch_rail",
    ),
    "gateway_technical_error": DocumentedReason(
        reason="gateway_technical_error",
        description="Technical error occurred at the gateway.",
        next_steps="Please retry after some time.",
        recovery_class="retry_same",
    ),
    "incorrect_card_details": DocumentedReason(
        reason="incorrect_card_details",
        description="Incorrect card details entered.",
        next_steps="Customer needs to enter correct card details.",
        recovery_class="nudge_customer",
    ),
    "incorrect_card_expiry_date": DocumentedReason(
        reason="incorrect_card_expiry_date",
        description="Incorrect card expiry date entered.",
        next_steps="Customer needs to enter the correct card expiry date.",
        recovery_class="nudge_customer",
    ),
    "incorrect_cvv": DocumentedReason(
        reason="incorrect_cvv",
        description=(
            "The customer has entered an incorrect CVV to complete the "
            "payment."
        ),
        next_steps="The customer must retry and enter the correct CVV.",
        recovery_class="nudge_customer",
    ),
    "incorrect_otp": DocumentedReason(
        reason="incorrect_otp",
        description=(
            "The customer has entered an incorrect OTP to complete the "
            "payment."
        ),
        next_steps="The customer must retry and enter the correct OTP.",
        recovery_class="nudge_customer",
    ),
    "incorrect_pin": DocumentedReason(
        reason="incorrect_pin",
        description="Incorrect PIN entered.",
        next_steps="Customer needs to enter the correct PIN.",
        recovery_class="nudge_customer",
    ),
    "input_validation_failed": DocumentedReason(
        reason="input_validation_failed",
        description=(
            "Payment failed due to wrong request or input sent in the "
            "payment request. This is also seen while creating a payment "
            "with incorrect parameter values on the Dashboard."
        ),
        next_steps=(
            "Rectify the validation issues and try again. Check the error "
            "description and field parameters for more information about "
            "the error."
        ),
        recovery_class="merchant_fix",
    ),
    "insufficient_funds": DocumentedReason(
        reason="insufficient_funds",
        description=(
            "The customer does not have sufficient funds in the account to "
            "complete the payment."
        ),
        next_steps="The customer must retry with a different card or method.",
        recovery_class="retry_later_funds",
    ),
    "international_transaction_not_allowed": DocumentedReason(
        reason="international_transaction_not_allowed",
        description="International transactions are not allowed.",
        next_steps=(
            "Customer needs to use a domestic payment method or enable "
            "international transactions."
        ),
        recovery_class="hard_stop",
    ),
    "invalid_order_id": DocumentedReason(
        reason="invalid_order_id",
        description=(
            "Order ID required in the payment request is either missing or "
            "is invalid. Order ID is mandatory for every payment."
        ),
        next_steps=(
            "Make sure the correct order ID is always passed while "
            "initiating a new payment."
        ),
        recovery_class="merchant_fix",
    ),
    "invalid_response_from_gateway": DocumentedReason(
        reason="invalid_response_from_gateway",
        description="Invalid response received from the gateway.",
        next_steps="Please retry the transaction.",
        recovery_class="retry_same",
    ),
    "invalid_vpa": DocumentedReason(
        reason="invalid_vpa",
        description=(
            "The customer has entered an incorrect VPA to complete the "
            "payment."
        ),
        next_steps="The customer must check and enter the correct VPA.",
        recovery_class="switch_rail",
    ),
    "issuer_technical_error": DocumentedReason(
        reason="issuer_technical_error",
        description="Technical error occurred at the card issuer.",
        next_steps="Please retry after some time or use another card.",
        recovery_class="retry_same",
    ),
    "order_already_paid": DocumentedReason(
        reason="order_already_paid",
        description=(
            "There can only be one successful payment for each order ID. "
            "This error arises when you are trying to use an order ID where "
            "a payment is already completed."
        ),
        next_steps=(
            "Check for order status before initiating a new payment attempt "
            "on the order."
        ),
        recovery_class="merchant_fix",
    ),
    "order_amount_mismatch": DocumentedReason(
        reason="order_amount_mismatch",
        description=(
            "This error arises when the amount mentioned in the order "
            "request is different from the amount mentioned in the payment "
            "request."
        ),
        next_steps=(
            "Please make sure that the same amount is passed in both "
            "payment and order request."
        ),
        recovery_class="merchant_fix",
    ),
    "otp_attempts_exceeded": DocumentedReason(
        reason="otp_attempts_exceeded",
        description="OTP attempts have been exceeded.",
        next_steps="Customer needs to wait and retry after some time.",
        recovery_class="retry_later_funds",
    ),
    "otp_expired": DocumentedReason(
        reason="otp_expired",
        description="The OTP has expired.",
        next_steps="Customer needs to request a new OTP.",
        recovery_class="nudge_customer",
    ),
    "payment_amount_tampered": DocumentedReason(
        reason="payment_amount_tampered",
        description="The payment amount has been tampered.",
        next_steps="The customer must retry with the correct amount.",
        recovery_class="hard_stop",
    ),
    "payment_cancelled": DocumentedReason(
        reason="payment_cancelled",
        description=(
            "The customer has explicitly cancelled the payment due to which "
            "the authentication failed to complete."
        ),
        next_steps="The customer must retry to complete the payment.",
        recovery_class="nudge_customer",
    ),
    "payment_collect_request_expired": DocumentedReason(
        reason="payment_collect_request_expired",
        description="The payment collect request has expired.",
        next_steps="Customer needs to retry the payment.",
        recovery_class="nudge_customer",
    ),
    "payment_declined": DocumentedReason(
        reason="payment_declined",
        description="The payment has been declined.",
        next_steps="Customer needs to retry with another payment method.",
        recovery_class="switch_rail",
    ),
    "payment_declined_due_to_high_traffic": DocumentedReason(
        reason="payment_declined_due_to_high_traffic",
        description="Payment declined due to high traffic at the gateway.",
        next_steps="Please retry after some time.",
        recovery_class="retry_same",
    ),
    "payment_failed": DocumentedReason(
        reason="payment_failed",
        description=(
            "Payment processing failed due to error at bank or wallet "
            "gateway. No specific error code received from gateway in this "
            "case."
        ),
        next_steps="Please retry with a different payment method.",
        recovery_class="retry_same",
    ),
    "payment_method_not_enabled": DocumentedReason(
        reason="payment_method_not_enabled",
        description=(
            "The selected payment method is not enabled for your business. "
            "This error occurs when your customer tries to complete a "
            "transaction using a method that is not enabled for you."
        ),
        next_steps="Reach out to Razorpay to enable payment method.",
        recovery_class="merchant_fix",
    ),
    "payment_risk_check_failed": DocumentedReason(
        reason="payment_risk_check_failed",
        description=(
            "Payment declined due to risk checks. Risk checks are performed "
            "by Razorpay, Gateway, and Issuer Bank. The source parameter "
            "would give additional clarity where the risk check failed."
        ),
        next_steps="The customer must retry with a different card or method.",
        recovery_class="hard_stop",
    ),
    "payment_session_expired": DocumentedReason(
        reason="payment_session_expired",
        description="The payment session has expired.",
        next_steps="Customer needs to start a new payment session.",
        recovery_class="nudge_customer",
    ),
    "payment_timed_out": DocumentedReason(
        reason="payment_timed_out",
        description=(
            "The customer did not complete the transaction within the "
            "specified time. This error may also happen when no response is "
            "received from the gateway."
        ),
        next_steps=(
            "The customer must retry and complete the transaction within "
            "the time."
        ),
        recovery_class="nudge_customer",
    ),
    "pin_attempts_exceeded": DocumentedReason(
        reason="pin_attempts_exceeded",
        description="PIN attempts have been exceeded.",
        next_steps="Customer needs to wait and retry after some time.",
        recovery_class="retry_later_funds",
    ),
    "psp_app_not_available": DocumentedReason(
        reason="psp_app_not_available",
        description=(
            "PSP app is not available. This can be because of a downtime "
            "with the PSP."
        ),
        next_steps="The customer must retry with another PSP app.",
        recovery_class="retry_same",
    ),
    "psp_not_available": DocumentedReason(
        reason="psp_not_available",
        description="PSP is not available.",
        next_steps="Customer needs to retry with another PSP.",
        recovery_class="retry_same",
    ),
    "request_timed_out": DocumentedReason(
        reason="request_timed_out",
        description="The request has timed out.",
        next_steps="Please retry the request.",
        recovery_class="retry_same",
    ),
    "server_error": DocumentedReason(
        reason="server_error",
        description=(
            "Technical error at Razorpay's server. This usually occurs when "
            "there is some server issue at Razorpay's end."
        ),
        next_steps="Please retry after some time or reach out to Razorpay.",
        recovery_class="retry_same",
    ),
    "transaction_daily_count_exceeded": DocumentedReason(
        reason="transaction_daily_count_exceeded",
        description="The daily transaction count has been exceeded.",
        next_steps=(
            "Customer needs to wait for the next day or use another payment "
            "method."
        ),
        recovery_class="retry_later_funds",
    ),
    "transaction_daily_limit_exceeded": DocumentedReason(
        reason="transaction_daily_limit_exceeded",
        description=(
            "The customer has exceeded the daily transaction limit set on "
            "the card. Some of the cards allow customers to set a limit or "
            "have a default limit set."
        ),
        next_steps=(
            "The customer must retry using a different instrument or wait "
            "24 hours to complete the payment."
        ),
        recovery_class="retry_later_funds",
    ),
    "transaction_frequency_limit_exceeded": DocumentedReason(
        reason="transaction_frequency_limit_exceeded",
        description=(
            "NPCI has a transaction limit both on the amount and the "
            "frequency per day. Customer has exhausted the frequency limit."
        ),
        next_steps="Please retry using another payment method.",
        recovery_class="retry_later_funds",
    ),
    "transaction_limit_exceeded": DocumentedReason(
        reason="transaction_limit_exceeded",
        description=(
            "The customers have exceeded the credit or debit limit set on "
            "their cards. This error usually arises while doing high value "
            "transactions."
        ),
        next_steps=(
            "The customer must retry using a different bank's card or "
            "method."
        ),
        recovery_class="retry_later_funds",
    ),
    "transaction_on_vpa_restricted": DocumentedReason(
        reason="transaction_on_vpa_restricted",
        description=(
            "Transaction on this VPA has been temporarily / permanently "
            "blocked by the PSP."
        ),
        next_steps="The customer to retry with another UPI ID.",
        recovery_class="switch_rail",
    ),
    "upi_app_technical_error": DocumentedReason(
        reason="upi_app_technical_error",
        description=(
            "Technical error occurred at the customer's PSP due to which "
            "the payment failed."
        ),
        next_steps=(
            "The customer must retry the payment. If the error persists "
            "then the customer should try using another UPI app."
        ),
        recovery_class="retry_same",
    ),
    "user_not_eligible": DocumentedReason(
        reason="user_not_eligible",
        description=(
            "The customer failed the eligibility check and is not eligible "
            "for credit. This error may arise when the customer has a poor "
            "credit score or incomplete / insufficient documents."
        ),
        next_steps="The customer must retry using a different payment method.",
        recovery_class="hard_stop",
    ),
    "user_not_registered_for_netbanking": DocumentedReason(
        reason="user_not_registered_for_netbanking",
        description="The customer's bank account is not registered for netbanking.",
        next_steps=(
            "The customer should register their account with the issuing "
            "bank for netbanking."
        ),
        recovery_class="switch_rail",
    ),
    "verification_failed": DocumentedReason(
        reason="verification_failed",
        description=(
            "Verification of the payment using the status check API has "
            "failed."
        ),
        next_steps="This is a temporary error. The customer must retry.",
        recovery_class="retry_same",
    ),
    "vpa_resolution_failed": DocumentedReason(
        reason="vpa_resolution_failed",
        description=(
            "The UPI network failed to validate the VPA. This is a "
            "technical error when the resolution fails."
        ),
        next_steps=(
            "The customer must retry using a different bank account or "
            "method."
        ),
        recovery_class="switch_rail",
    ),
}

# Reasons Razorpay documents as risk, compliance or merchant-side integration
# failures. Re-presenting one of these is not merely wasteful: programmatically
# retrying a risk-declined payment is the behaviour that gets a merchant's MID
# reviewed. agent/policy.py treats this set as a hard veto that the model cannot
# talk its way past.
NEVER_RETRY: frozenset[str] = frozenset(
    r for r, d in RULEBOOK.items() if d.recovery_class in ("hard_stop", "merchant_fix")
)

# Razorpay documents this reason as carrying no specific gateway error code, so
# the string alone cannot tell you what went wrong. The right action has to be
# inferred from context: method, issuer health, amount, customer history.
AMBIGUOUS: frozenset[str] = frozenset({"payment_failed"})


def documented_class(reason: str) -> str | None:
    """The recovery class Razorpay's docs imply, or None if unmapped.

    `None` is the interesting case. It means either a reason our rulebook has
    not caught up with, or one Razorpay documents ambiguously. Either way the
    agent is on its own.
    """
    entry = RULEBOOK.get(reason)
    return entry.recovery_class if entry else None


def describe(reason: str) -> str:
    """Razorpay's own description, for feeding to a model. Falls back to the
    raw reason string when we have no entry -- which is precisely when the
    model has to work hardest."""
    entry = RULEBOOK.get(reason)
    return entry.description if entry else f"(undocumented reason: {reason})"


KNOWN_REASONS: frozenset[str] = frozenset(RULEBOOK)
